### ISSUE TITLE
Editing projects file error

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#11]
I've made a mistake on the group name, therefore I'm trying to edit the `Dashboard projects.json` file; although when I go ahead to save the file I'm informed that the *editing projects file does not meet the schema expected by dashboard* ?

**Comment by Kruemelkatze** [comment]
Would you mind posting your projects.json file? :)

It basically fails the validation shown below. It would be great if you could work out what is incorrect in your file. If that's a bug, I'll gladly recheck and fix it!

```ts
                // Validate
                var jsonIsInvalid = false;
                if (Array.isArray(updatedProjectGroups)) {
                    for (let group of updatedProjectGroups) {
                        if (jsonIsInvalid || !group || !group.id || group.groupName == undefined || !group.projects || !Array.isArray(group.projects)) {
                            jsonIsInvalid = true;
                            break;
                        } else {
                            for (let project of group.projects) {
                                if (!project || !project.id || !project.name || !project.path) {
                                    jsonIsInvalid = true;
                                    break;
                                }
                            }
                        }
                    }
                } else {
                    jsonIsInvalid = true;
                }
```

**Comment by SheepDomination** [comment]
Below you will find my `projects.json` file.
```
[
    {
        "id": "mari[python]z5om8ti77jtygyccn",
        "groupName": "Mari [Python]",
        "projects": [
            {
                "isGitRepo": false,
                "id": "houdinivex752ugi8cpjtygzzkp",
                "name": "Houdini VEX",
                "path": "c:\\Custom Program Settings\\Projects.Code\\VEX",
                "imageFileName": null,
                "color": "var(--vscode-gitDecoration-conflictingResourceForeground)"
            }
        ]
    },
    {
        "id": "ppdo50avwjtyh1qlk",
        "projects": []
    },
    {
        "id": "dtnbnzp24jtyh2rz9",
        "projects": []
    }
]
```

**Comment by SheepDomination** [comment]
@Kruemelkatze Any update ?

**Comment by Kruemelkatze** [comment]
@SheepDomination, yes! Sorry for not getting back to you, I forgot about this, to be honest...
BUT! I spent quite some time in the last days on v1.3, which delivers some new features and "fixes" your problem. I will publish it in the next few days (some colleages are currently testing it).

The problem with your file were simply the two empty project groups. Remove them and saving will work. v1.3 will remove empty groups without name in future in order to not pollute the file.
```json
[
    {
        "id": "mari[python]z5om8ti77jtygyccn",
        "groupName": "Mari [Python]",
        "projects": [
            {
                "isGitRepo": false,
                "id": "houdinivex752ugi8cpjtygzzkp",
                "name": "Houdini VEX",
                "path": "c:\\Custom Program Settings\\Projects.Code\\VEX",
                "imageFileName": null,
                "color": "var(--vscode-gitDecoration-conflictingResourceForeground)"
            }
        ]
    }
]
```

Sorry that you had to wait that long!

**Comment by SheepDomination** [comment]
Is it possible to toggle the `path` value between being displayed and not being displayed ? Also can you add an icon ?

**Comment by SheepDomination** [comment]
@Kruemelkatze Can you add SVG or PNG files rather then Windows emijoi's ?

**Comment by Kruemelkatze** [comment]
@SheepDomination
- Toggling ```path``` display is currently not possible, but I may have a look at that.
- I initially tried to have icon/image files per project, but ran into all kinds of problems because vscode severely limits the access to resources. And handling them as base64 is tough, so I  canceled that feature.
- You mean having the project groups align in columns rather than rows?
- The color of a tile is set by border-color, which does not support gradients. For gradients, I may have to build some kind of workaround using border-image. That goes along with all kinds of switches in the entry & display functions, so I guess I won't implement that for now. Sorry.

**Comment by SheepDomination** [comment]
> - Toggling path display is currently not possible, but I may have a look at that.

I would appreciate this option.

> - I initially tried to have icon/image files per project, but ran into all kinds of problems because vscode severely limits the access to resources. And handling them as base64 is tough, so I canceled that feature.

I have to convert my images to emojis then load them into Windows then I can use custom icons; and creating emojis is, as I found out recently, bit of a pain.

> - You mean having the project groups align in columns rather than rows?

When you create a new project tile and give each project tile it's own group; all the groups are aligned as columns, rather then rows.  I'm assuming if you give some project tiles a single group name, rather then each project tile having their own group name, those groups align in rows, rather then columns ?

> - The color of a tile is set by border-color, which does not support gradients. For gradients, I may have to build some kind of workaround using border-image. That goes along with all kinds of switches in the entry & display functions, so I guess I won't implement that for now. Sorry.

You mean the CSS property `border-color`, correct; as in, `border-color: rgba(201, 76, 76, 0.3);` ? Except it has to be written in JSON format.

**Comment by Kruemelkatze** [comment]
> > * Toggling path display is currently not possible, but I may have a look at that.
> 
> I would appreciate this option.

I released **v1.3** today which includes that option! :)

> > * You mean having the project groups align in columns rather than rows?
> 
> When you create a new project tile and give each project tile it's own group; all the groups are aligned as columns, rather then rows. I'm assuming if you give some project tiles a single group name, rather then each project tile having their own group name, those groups align in rows, rather then columns ?

Projects are not intended to each have their own project group. They are intended to group projects into a row/multiple rows.
My dashboard for example looks something like this: [https://imgur.com/a/toDOUuw](https://imgur.com/a/toDOUuw)

> > * The color of a tile is set by border-color, which does not support gradients. For gradients, I may have to build some kind of workaround using border-image. That goes along with all kinds of switches in the entry & display functions, so I guess I won't implement that for now. Sorry.
> 
> You mean the CSS property `border-color`, correct; as in, `border-color: rgba(201, 76, 76, 0.3);` ? Except it has to be written in JSON format.

Currently, the code does basically this:
```
.project {
    border-top-color: ${project.color};
}
```

Only the project data is in JSON, the displaying is done via native CSS in the Webview. And as the ```border-top-color``` property does not support gradients, I would have to rewrite this to use ```border-image: ...``` or ```border-image-source: ...```. Manually entering gradients in the current scheme (by editing the projects via command) will result in simply ignoring the property.

**Comment by SheepDomination** [comment]
Is there a list of variables that I can use in JSON to style the tiles; as you used, `${project.color};` ?
Can you add in the next, possibly dot released to use `border-image`,`border-image-source` etc ? 

Also what is the issue that you can't use PNG or SVG images ?

**Comment by Kruemelkatze** [comment]
> Is there a list of variables that I can use in JSON to style the tiles; as you used, `${project.color};` ?
Any [CSS Color](https://www.arclab.com/en/kb/htmlcss/html-css-color-names-rgb-rgba-hex-hsl-hsla.html).

> Can you add in the next, possibly dot released to use `border-image`,`border-image-source` etc ?
I'll have a look on it!

> Also what is the issue that you can't use PNG or SVG images ?
To store images in an extension, you either need to save them in the file system or base64-encoded within the project. When it comes to load files in a webview, vscode is [very restrictive](https://code.visualstudio.com/api/extension-guides/webview#security). Base64-encoded images are easier to handle but may decrease the extensions performance if users provide bigger files. All in all, the use-case for project images/logos was quite limited and emojis provided a much simpler solution.

**Comment by SheepDomination** [comment]
Any border css style will work, any other styles I should be aware of that will work ? I tried `border` and it didn't work for the tile ?

> To store images in an extension, you either need to save them in the file system or base64-encoded within the project. When it comes to load files in a webview, vscode is very restrictive. Base64-encoded images are easier to handle but may decrease the extensions performance if users provide bigger files. All in all, the use-case for project images/logos was quite limited and emojis provided a much simpler solution.

Alright, thanks for the info on this question; hopefully in the future this improves.

**Comment by SheepDomination** [comment]
@Kruemelkatze Does this extension have pre-defined variables ?

**Comment by Kruemelkatze** [comment]
> Any border css style will work, any other styles I should be aware of that will work ? I tried `border` and it didn't work for the tile ?

As I said, I simply set the border-color to the value given to the project. Any other border-related properties cannot be set currently.

> Does this extension have pre-defined variables ?

Depends on what you mean by variable ;)
For colors, I use three colors defined by the current theme (so they change when switching theme):
```scss
:root {
    --dashboard-project-card-bg: var(--vscode-tab-inactiveBackground);
    --dashboard-foreground: var(--vscode-editor-foreground);
    --dashboard-path: var(--vscode-descriptionForeground);
}
```

> If you were to base64-encode an image, I assume you place the code into the project name and the icon would appear ?

That could actually work, if you provide the full ```<img src="data:image/gif;base64,..." />``` tag!

**Comment by SheepDomination** [comment]
>Depends on what you mean by variable ;)
For colors, I use three colors defined by the current theme (so they change when switching theme):

Pre-defined variables such as the following;  `${project.color};`  And as you mentioned; `dashboard-project-card-bg` ?

**Comment by Kruemelkatze** [comment]
> > Depends on what you mean by variable ;)
> > For colors, I use three colors defined by the current theme (so they change when switching theme):
> 
> Pre-defined variables such as the following; `${project.color};` And as you mentioned; `dashboard-project-card-bg` ?

Check here:
https://github.com/Kruemelkatze/vscode-dashboard/blob/master/src/webviewContent.ts#L139
https://github.com/Kruemelkatze/vscode-dashboard/blob/master/src/webviewContent.ts#L66

**Comment by SheepDomination** [comment]
In version 1.4 editing projects now correctly sets color ? 
How about gradients on groups ?

**Comment by Kruemelkatze** [comment]
> In version 1.4 editing projects now correctly sets color ?
Yep, had a bug that editing a project via the dashboard didn't save the color in some cases.

> How about gradients on groups ?
As the groups are only used as a loose grouping and have no card themselves, additional colored elements would be too much imho.

I'm also closing this issue, as the initial problem and the request for gradients have both been solved. :)

**Comment by SheepDomination** [comment]
In the recent version of Dashboard modifying and saving the `Dashboard Projects.json` file doesn't commit to the changes ?

**Comment by Kruemelkatze** [comment]
Thanks for reporting!
Will have a look on this.

**Comment by Kruemelkatze** [comment]
This was a bug related to storage consistency (globalState vs settings) and related to #37. I just released v.2.0.2 that fixes it.

Please note: You may lose the latest changes in the dashboard. Sorry for that!
Having two datasources I do not have full control over gives me headaches... :-)
