### ISSUE TITLE
Make add button smaller

### ISSUE THREAD

**Issue by GammaGames** [Kruemelkatze/vscode-dashboard#13]
I propose that instead of having a large `+` square in each group, there could be a small `+` square next to the group name. Right now I have one row that is completely empty aside from the add button and it takes up a lot of space.

**Comment by Kruemelkatze** [comment]
Thanks for the suggestion! I'll try this and may add it as an option, as I don't want to "break" the UI.

**Comment by Kruemelkatze** [comment]
I just released **v1.5** which includes an option for this! :)

[Full Changelog](https://github.com/Kruemelkatze/vscode-dashboard/blob/1.5/CHANGELOG.md)

**Comment by GammaGames** [comment]
Works great, thank you!
