### ISSUE TITLE
Option to Automatically Start Dashboard

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#15]
Rather then having to always start Dashboard though the command palette.  I would like Dashboard to automatically start each time I start code.
Although when starting loading a project, I don't want it to remove existing tabs, just append the project to the current open tabs.

**Comment by GammaGames** [comment]
I added a chord shortcut so I could easily open the dashboard with the following keybinding:

```
  {
    "key": "ctrl+k d",
    "command": "dashboard.open"
  },
```

**Comment by Kruemelkatze** [comment]
Apart from that there was already a shortcut for this (ctrl + f1), I just released **v1.5** which includes an option for setting the startup behaviour to always, never or on empty workspace! :)

[Full Changelog](https://github.com/Kruemelkatze/vscode-dashboard/blob/1.5/CHANGELOG.md)

**Comment by SheepDomination** [comment]
There is not an option to append the current workspace files, only replace them ?

**Comment by SheepDomination** [comment]
Appending would be extremely beneficial.

**Comment by vith** [comment]
> I just released **v1.5** which includes an option for setting the startup behaviour to always, never or on empty workspace! :)

I'm using the default `"dashboard.openOnStartup": "empty workspace"`, but when I open a new vscode window via the File menu or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>, only an empty `Untitled-1` file appears.

Is this a bug or am I misunderstanding something?

Might be because I use `"window.restoreWindows": "all"`?

**Comment by Kruemelkatze** [comment]
That's intended behaviour, because, when you open a new file, your workspace is not empty, so the dashboard does not open. If you need a new vscode window with the dashboard showing, you can use File > New Window.

I think that's not affected by ```window.restoreWindows```.

**Comment by vith** [comment]
> If you need a new vscode window with the dashboard showing, you can use File > New Window.

That's what I was trying and I don't get the dashboard there automatically. I'll set up a new VSCode install in a VM and see if it behaves differently. Maybe it's a conflict with other extensions I have.

**Comment by Kruemelkatze** [comment]
> > If you need a new vscode window with the dashboard showing, you can use File > New Window.
> 
> That's what I was trying and I don't get the dashboard there automatically. I'll set up a new VSCode install in a VM and see if it behaves differently. Maybe it's a conflict with other extensions I have.

Ah, my bad! I somehow read that you opened a new file.

Can you check what your ``"workbench.startupEditor":``` is set to? If it is set to ```"newUntitledFile"```that's the reason why. :)

**Comment by vith** [comment]
Yep, it works in a clean install until I uncheck this:

![image](https://user-images.githubusercontent.com/3265539/68510516-5f17ad00-0239-11ea-8c7b-106b086e65d4.png)

`"workbench.startupEditor": "welcomePage"`

vs

`"workbench.startupEditor": "newUntitledFile"`

I guess technically that's not an empty workbench then. Pretty surprising though IMO. Maybe it should be a special handled case :P

**Comment by Kruemelkatze** [comment]
> I guess technically that's not an empty workbench then.

This. ;)

There's the option for ```"workbench.startupEditor": "newUntitledFile"``` for opening only the dashboard in a new, empty window. I will handle the above case as ***not an empty workspace***, but maybe will add an info to this native setting to the ```dashboard.openOnStartup```setting!
