### ISSUE TITLE
Enhancement Request: Remote and Recent Projects

### ISSUE THREAD

**Issue by KrishKasula** [Kruemelkatze/vscode-dashboard#16]
Hello @Kruemelkatze 

First of all great extension.

Do you have any plans for adding support for Remote Projects
https://code.visualstudio.com/docs/remote/remote-overview

Also, how about capturing the recent projects as they appear in VSCODE's start page

-
Krishna

**Comment by Kruemelkatze** [comment]
Hey! Thank you! :)

Some reddit users also suggested this feature. I tried a bit around:
- Opening remote projects works just fine
- I'm trying to use the connection list of the Remote Extension, as I do not want to store connection information (which may be credentials!) in the dashboard extension data store. I'm still struggling with that.

It's definitely a feature that will be implemented in one way or another! :)

**Comment by KrishKasula** [comment]
Hi Kruemelkatze,

I am no expert in vscode extensions but I use no credintials to login to
remote project
I use SSH public key instead. Does it do any help?

I would be glad to be beta tester for that version by the way :)

Cheers
Krishna

**Comment by Kruemelkatze** [comment]
I just released **v1.5** which introduces support for **SSH targets**, including opening remote folders, just as the Remote Development extension! :)

WSL and Container remotes are not supported (yet?) as Dashboard projects, as they function differently and there is no documentation for this. For getting SSH targets to work, I had to grub through the Remote Development extension's sourcecode 😶.

I got a couple of colleagues to betatest this, but please keep an eye out for problems! :)

[Full Changelog](https://github.com/Kruemelkatze/vscode-dashboard/blob/1.5/CHANGELOG.md)

**Comment by dufferzafar** [comment]
@Kruemelkatze Can you point me to where the Remote SSH source code is available on GitHub? 

I think the current way is to just download the .vsix package from Marketplace and browse the code from there?

**Comment by dufferzafar** [comment]
Also, I'm not sure how I can add recent projects that I find in the quick switcher list to the dashboard.

**Comment by Kruemelkatze** [comment]
> @Kruemelkatze Can you point me to where the Remote SSH source code is available on GitHub?
> 
> I think the current way is to just download the .vsix package from Marketplace and browse the code from there?

Unfortunately, yes. I had to do the same when trying to figure out what the correct commands for opening SSH remote projects are.

> Also, I'm not sure how I can add recent projects that I find in the quick switcher list to the dashboard.

There is no dedicated function in the dashboard for doing so. You can either add them by browsing to their local folder (or entering the ssh remote address) or (currently for local-projects only) open them and add a new project - the default picker location is the currently opened workspace.

**Comment by dufferzafar** [comment]
> You can either add them by browsing to their local folder (or entering the ssh remote address)

It currently fails with remote paths that have spaces in their name.

I tried: `szafar@remote.com/spare/ssd/szafar/projects/Harry Potter.code-workspace`

**Comment by Kruemelkatze** [comment]
> > You can either add them by browsing to their local folder (or entering the ssh remote address)
> 
> It currently fails with remote paths that have spaces in their name.
> 
> I tried: `szafar@remote.com/spare/ssd/szafar/projects/Harry Potter.code-workspace`

Ah, good to know! I'll fix this and release an update!

**Comment by Kruemelkatze** [comment]
@dufferzafar Would you mind testing it out with this version?

[vscode-dashboard-2.1.3-preview.vsix.zip](https://github.com/Kruemelkatze/vscode-dashboard/files/4566233/vscode-dashboard-2.1.3-preview.vsix.zip)
