### ISSUE TITLE
json path

### ISSUE THREAD

**Issue by tobiaswaelde** [Kruemelkatze/vscode-dashboard#17]
Where do you store the Dashboard Projects.json?

I use [VS Code Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) and want to sync the dashboard across multiple devices.

**Comment by scadaguru** [comment]
Wow! It took some time to find that folder location for me, I was looking under VS Code installation.
Here it is for me: (where xxxx is Windows user), Worried little bit about location in temp folder though.
C:\Users\xxxxx\AppData\Local\Temp\Dashboard Projects.json
Hope this helps.

**Comment by Kruemelkatze** [comment]
Hey!
Don't be bamboozled. That Dashboard Projects.json file is **not used for storing** the projects. It is only a temp file (hence the location) for editing the projects manually!
The projects are stored in VS Code's **globalState**. I do not think that VS Code Settings Sync works with this.
But I've seen [this update log](https://code.visualstudio.com/updates/v1_31#_global-storage-path) so I will have a look on this and maybe migrate the data.

I'll keep you up to date on this.
