### ISSUE TITLE
Enhancement Request: Reorder Project Groups

### ISSUE THREAD

**Issue by chenpion** [Kruemelkatze/vscode-dashboard#18]
First, this is a great extension, loved it a lot.
It would be greater if it supports ordering groups.

**Comment by Rockin4Life33** [comment]
Agreed!  Great extension!
I also was going to put in a request to allow groups to be reordered; @chenpion beat me to it.  I look forward to upcoming features!

**Comment by Kruemelkatze** [comment]
I just released **v1.5**, which includes this and other UI functions for adding, editing, reordering projects and groups! :)

[Full Changelog](https://github.com/Kruemelkatze/vscode-dashboard/blob/1.5/CHANGELOG.md)
