### ISSUE TITLE
Dashboard Icon in Activity Bar

### ISSUE THREAD

**Issue by webdevnerdstuff** [Kruemelkatze/vscode-dashboard#19]
I would be really nice to have the ability to have an icon in the Activity Bar to open up the Dashboard.  Would it possible for you to add this as a new enhancement? Thank you.

**Comment by Kruemelkatze** [comment]
I already wanted to implement this - so yes, will do, if possible! :)
I'll have to check the vscode API, if opening custom views from the Activity Bar is supported. The other  extensions I use only open a side menu.

**Comment by webdevnerdstuff** [comment]
I hadn't even thought if it's possible. I did some digging but couldn't find anything in the API that allows the Activity Bar Icon to open a Webview (I assume what it's doing currently). When I have some more time I'll do some more digging. I haven't gotten too deep into the API yet, I've only gotten my feet a little wet.

**Comment by Kruemelkatze** [comment]
Looks like the devs [over there](https://github.com/Microsoft/vscode/issues/46585) have the same problem.

**Comment by SheepDomination** [comment]
What about Dashboard in Web view ?

**Comment by Kruemelkatze** [comment]
I invested some hours into this and as it looks, there is no support for opening webviews out of activity bar icons in the current vscode API.

I'll keep this issue open if something good happens. :)

> What about Dashboard in Web view ?
Still active! I just released v1.5.

**Comment by webdevnerdstuff** [comment]
I had a feeling that was the case. I searched quite a bit myself and wasn't able to find any solution, but I did find support tickets from people who do want this functionality.

**Comment by SheepDomination** [comment]
You can add Dashboard by means of the Activitus Bar Extension.

**Comment by Kruemelkatze** [comment]
Oh, nice! I'll have a look if I can add this automatically. :)
Thanks!

Having a naming (I saw your discussion in the Activitus Bar Repo) would be nice though.

**Comment by sghsri** [comment]
Hey! I love this extension and wanted to know if this was still being worked on?

**Comment by Kruemelkatze** [comment]
Hey! I still check every now and then if a VSCode API feature for this has been introduced. As of now, this is sadly still not possible...

**Comment by azchatlanin** [comment]
This app https://github.com/fabiospampinato/vscode-projects-plus can add icon on active bar. Maybe will search decisions in src.

**Comment by Kruemelkatze** [comment]
> This app https://github.com/fabiospampinato/vscode-projects-plus can add icon on active bar. Maybe will search decisions in src.

That is quite similar to what the [Project Manager](https://github.com/alefragnani/vscode-project-manager) extension does. Both are adding a (tree-)list to the activity bar, which is supported by the vscode API. Opening the custom dashboard view is the thing that does not work yet.

**Comment by SheepDomination** [comment]
I assume the opening of the custom dashboard view is related to visual studio code API ?

**Comment by surajmandalcell** [comment]
Any update on this?

This is a great extension and ctrl+shift+p > "dashboard: open" works but it gets tedious after some time. The activity bar or even a status bar icon would be awesome!

**Comment by Kruemelkatze** [comment]
> Any update on this?

Unfortunately not, [this issue at the vscode repo](https://github.com/Microsoft/vscode/issues/46585) is the main one tracking the feature of using custom from Activity Bar icons and it's still open.

> This is a great extension and ctrl+shift+p > "dashboard: open" works but it gets tedious after some time. The activity bar or even a status bar icon would be awesome!

You can always use CTRL + F1 to open the dashboard quickly or assign any other shortcut to the action! :-)
The [Activitus Bar extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar) offers the possibility of adding clickable icons to the status bar. This was discussed [over here](https://github.com/Gruntfuggly/activitusbar/issues/27). Afaik you can only use in-built icons for this though.


> I assume the opening of the custom dashboard view is related to visual studio code API ?

Yes, all extensions are based on the vscode API by definition. ;)
The main problem here is: Extensions can add any icon to the Activity Bar, but currently, this custom icon can only be used to create **vscode-native UI**, namely (tree-)lists. The vscode API currently does not support triggering any other action from an activity bar icon. That's why every extension out there that uses activity bar icon (e.g. Project Manager, GitLens) only opens a tree list with it.

**Comment by kalvinpearce** [comment]
Looks like they have now [implimented this](https://github.com/microsoft/vscode/issues/46585) in version 1.50. Would love to see this beautiful extention in the sidebar

**Comment by Kruemelkatze** [comment]
Thanks for the update! Will have a look at this in the next days! :)

**Comment by Kruemelkatze** [comment]
I had a look on this in the last days, and so far I only could achieve to show an additional webview in the sidebar. As far as I understand, that's what the new API is supposed to be for... But it's still not designed for executing any other actions - such as opening the dedicated dashboard view - by clicking on a sidebar icon. I managed to show the main dashboard when the sidebar variant is opened, but that's still more a hack than anything else. The vscode folks are keeping their rules and API very strict to keep the UI consistent. 😉

If somebody has any idea on this, please let me know.

![image](https://user-images.githubusercontent.com/5564731/99589281-0e11cb80-29ec-11eb-93ed-3055f46dc54b.png)

**Comment by surajmandalcell** [comment]
Looks good but instead of webview can there be an option for it to just be a link to the dashboard? So for example, if I click on it it would open the dashboard page.

This would save me a lot of steps 😄  `cmd+shift+p` -> `dashboard` -> enter

This is just an opinion tho since we don't have anything reliable solution for activity bar yet.

**Comment by Kruemelkatze** [comment]
> Looks good but instead of webview can there be an option for it to just be a link to the dashboard somewhere, activity bar or literally anywhere on the screen somehow 😢 I just want to click on it for it to open the dashboard.
> 
> This would save me a lot of steps `cmd+shift+p` -> `dashboard` -> enter
> 
> This is just an opinion tho since we don't have any reliable solution yet other than command palette.

That's exactly what I want to achieve but currently struggle to do. 😉

In the meantime, you can use the default keyboard shortcut CTRL+F1 to open the dashboard. Or you can use the [Activitus Bar](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar) to add an icon below the activity bar. Unfortunately, these icons are tiny. The command for opening the dashboard is ```dashboard.open```.

**Comment by Kruemelkatze** [comment]
I got the sidebar icon to work and just unleashed my testers on the feature! Will hopefully release an update soon. 😊

**Comment by Kruemelkatze** [comment]
I just released version 2.3.0, which added a sidebar icon for the dashboard. You may notice that the sidebar opens and immidiately closes, but sadly I can't do anything against this right now.
