### ISSUE TITLE
Git / Github Organizations

### ISSUE THREAD

**Issue by jschr** [Kruemelkatze/vscode-dashboard#2]
Hey, saw your reddit post, great idea! I will be playing around with this.

Random idea that would be really awesome (IMO) would be to connect to github and create a dashboard for a particular organization. 

This would personally help me a ton (I have to switch between repos all day at my company). 

Just wanted to share my gratitude + offer unsolicited feature requests :) 

Feel free to close!

**Comment by alexweininger** [comment]
> Hey, saw your reddit post, great idea! I will be playing around with this.
> 
> Random idea that would be really awesome (IMO) would be to connect to github and create a dashboard for a particular organization.
> 
> This would personally help me a ton (I have to switch between repos all day at my company).
> 
> Just wanted to share my gratitude + offer unsolicited feature requests :)
> 
> Feel free to close!

I second the connecting with github feature!  If this feature is pursued, I would want there to be a way of easily separate/organize your local git repos / workspaces from github repos.

A great idea and a great extension!

**Comment by Kruemelkatze** [comment]
Thanks for your feedback and kind words! :)

As I understand this feature: You would like to select a GitHub User/Organization (by providing the URL e.g.). The extension then fetches all projects in that User/Org and created projecs on the dashboard.

> I second the connecting with github feature! If this feature is pursued, I would want there to be a way of easily separate/organize your local git repos / workspaces from github repos.

Great idea! I think giving a general option for grouping projects would be nice. I'll make some mockups. ;)

**Comment by jschr** [comment]
The idea of having a tighter integration with git is really interesting because you could provide git shortcuts right in the dashboard for each project card. Some challenges I think the idea could solve are:

- Seeing which repos are behind in commits (maybe showing the latest commit message)
- Seeing which repos have open PRs (maybe showing which are pending my approval)
- Seeing the build status of each repo (which branch is failing?)

**Comment by tecosaur** [comment]
One small thing for git, would be something like showing a small git icon in the upper left corner if a `.git` folder exists in the workspace.
