### ISSUE TITLE
Hitting escape removes already entered text

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#21]
I wrote a post [here](https://www.reddit.com/r/vscode/comments/dljqro/vscode_dashboard_v15/f4vaz10?utm_source=share&utm_medium=web2x) already but I might as well file a report here.

So my project group is called "Private" & when I click on editing it & then press Escape, it removes everything & renames it to "Unnamed Project Group".

In theory or by UX perspective, it should keep it as "Private". So this might be a bug :)

**Comment by Kruemelkatze** [comment]
Oh, didn't get a notification for this issue.
Anyway, as mentioned: v1.5.1 resolves this! :)
