### ISSUE TITLE
Open in New Window

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#25]
I really love this extension now that I've used it for a couple of days & it helps bcz I have multiple projects at the same time.

So what I want is open in a new window icon like https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-external-link

I hate it when I click it & it opens it in the same window. Is it possible to do this?

**Comment by Kruemelkatze** [comment]
You can ctrl+click to open the project in a new window! :)
I'll try not to use too many icons, so I won't add one for this, I'm afraid.

**Comment by deadcoder0904** [comment]
@Kruemelkatze Ctrl+Click doesn't really work on my Mac I'm afraid

**Comment by Kruemelkatze** [comment]
Oh, you learn something you every day. 🤔

I changed ```clickEvent.ctrlKey``` to ```clickEvent.ctrlKey || clickEvent.metaKey``` [here](https://github.com/Kruemelkatze/vscode-dashboard/blob/master/src/webviewContent.ts#L195) and attached a preview version. Can you please try if it works on Mac? :)

[vscode-dashboard-1.5.3-preview.vsix.zip](https://github.com/Kruemelkatze/vscode-dashboard/files/3794082/vscode-dashboard-1.5.3-preview.vsix.zip)

**Comment by deadcoder0904** [comment]
I tried disabling it & then installing from `.vsix` but I'm afraid I'm not able to open the extension itself so no way of checking anything else 😂

**Comment by Kruemelkatze** [comment]
Did you do that via the command ***Extensions: Install from VSIX..."?
That always works for me and my betatesters. 😃

**Comment by deadcoder0904** [comment]
Yes I did it thats why I said I installed it & it gave this notification  👇

![image](https://user-images.githubusercontent.com/16436270/67954423-f74cdb00-fc16-11e9-88d4-9924fd56bc2a.png)

But when I press ⌘+F1 it doesn't open. Nor I can find it by pressing ⌘+P through "Search"

**Comment by deadcoder0904** [comment]
Even tried refreshing VSCode :)

**Comment by Kruemelkatze** [comment]
I guess you already had >= 1.5 installed before? Also, whats your VSCode version?
I needed to bump the required VSCode version to 1.39 for the 1.5 release. Don't know what happens if you install an extension manually and your version is < 1.39. 😁

**Comment by deadcoder0904** [comment]
⌘+Click worked :)

I have 1.5.3-preview now so I guess that's why, thanks 🙌

**Comment by SheepDomination** [comment]
Rather then replace all the files you are working on in the current workspace, why not append; that is still not implemented ?
