### ISSUE TITLE
Improve Onboarding

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#26]
It's really confusing how to make a `Project Group` & a `Project` inside of it.

The most simple thing you can do probably is separate those 2 commands.

One for "Create Group" & other for "Create Project" . Also, renaming "Project Group" to just "Group" or "Collection" seems much better & not confusing.

When new group is created, you can keep the projects empty & not ask it again & just mention a plus sign if someone wants to add a project.

Also, need a way to change color. Just color & not go through the whole 3-step process just to change the color. You can take inspiration from https://github.com/johnpapa/vscode-peacock for default colors, random colors, darken, lighten, etc...

Hope this helps 🤞

**Comment by deadcoder0904** [comment]
Also, look at https://github.com/kitze/JSUI which does the same thing & I really liked it's onboarding which was too simple to understand.

My only gripe with Dashboard was it was difficult to understand the first 2-3 times but now that I know I can do it but this might be very helpful for beginners getting started with the extension & it's a cool extension which I think has the potential to be popular :)

**Comment by Kruemelkatze** [comment]
I'll agree that the organization is not quite intuitive. When adding new stuff, I didn't want to break the old UI. Maybe it's time for a revamp, but that would be a thing for a bigger 2.0 release which will take some time.

Thanks for the inspiration! :)

**Comment by deadcoder0904** [comment]
Another thing I noticed is the animation coming from the top for icons are slow. They should be fast (<200ms is perceived as fast I think)

**Comment by Kruemelkatze** [comment]
I just released **v2.0.0** that made the UI as well as all actions simpler and more consistent. I even added a "recent colors" options, similar to Peacock.
Thanks for your suggestions! :)

**Comment by deadcoder0904** [comment]
Damn that was 6 months ago. Time flies 🚀 

TYSM for your hard work 💯

**Comment by Kruemelkatze** [comment]
Totally. Originally, I intended to do most of this stuff during the Christmas holidays. But then stuff happened and it was April... ;)
