### ISSUE TITLE
Appending files instead of replacing

### ISSUE THREAD

**Issue by Kruemelkatze** [Kruemelkatze/vscode-dashboard#28]
Rather then replace all the files you are working on in the current workspace, why not append; that is still not implemented ?

_Originally posted by @SheepDomination in https://github.com/Kruemelkatze/vscode-dashboard/issues/25#issuecomment-550155753_

**Comment by Kruemelkatze** [comment]
@SheepDomination

What do you mean? 
- When opening the dashboard, files are replaced with the dashboard? If that's the case, some other extension is interfering. When opening the dashboard I simply open a new tab and don't tell anything to close.
- Opening a project closes your current one with all the open files. And you want to attach them instead? That's the default **"Open Folder"** and **"Open Workspace"** behavior of VSCode that the dashboard calls. So I won't change that.

> that is still not implemented ?

Feel free to fork for your special wishes.

**Comment by SheepDomination** [comment]
@Kruemelkatze When I open a project from Dashboard, it always ask me to replace my current tabs with that of the project within Dashboard, it never asks me; if I would like to append the current workspace, with what I'm already working with.  

Which brings me to another question, is it possible to nest tabs, you open a workspace and it appends to your current workspace but within a tab, then clicking that tabs open all the tabs of the workspace from Dashboard ?

**Comment by Kruemelkatze** [comment]
> @Kruemelkatze When I open a project from Dashboard, it always ask me to replace my current tabs with that of the project within Dashboard, it never asks me; if I would like to append the current workspace, with what I'm already working with.

As I said, that's the native behavior of VSCode when opening a new workspace or folder. The dashboard only triggers these native commands. Even if I wanted to (which I do not), I doubt if I could change that behaviour.

But: When I have unsaved files and try to open another project, it asks if I want to change the workspace:
![image](https://user-images.githubusercontent.com/5564731/68304072-568e6d80-00a5-11ea-86c6-c58903e35f6b.png)


> Which brings me to another question, is it possible to nest tabs, you open a workspace and it appends to your current workspace but within a tab, then clicking that tabs open all the tabs of the workspace from Dashboard ?

I guess not, VSCode is quite limited when it comes to UI options. Also, the dashboard does not open tabs per se. It only tells VSCode to open a folder (or workspace file or remote), VSCode appends the recent open tabs of that folder/ws/remote afterwards.

**Comment by SheepDomination** [comment]
Bummer, hopefully in the future Microsoft changes this.
