### ISSUE TITLE
Do not ask about Project Group when I click on + besides Project Group

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#30]
This is a weird one. But yeah don't ask which project group I want to add a new project in when I click besides a project group.

The only thing here that bugs me here is if I want to add a new Project Group. I think this can be moved to the explorer.

**Comment by Kruemelkatze** [comment]
I agree! It's still one of those "New feature, but I don't want to break old workflow" things.
As said in your "Onboarding" issue, I'll revamp the adding/editing workflow in a 2.0 version as soon as I have more spare time. :)

**Comment by deadcoder0904** [comment]
Yep just created a new issue to keep track of it ;)

**Comment by Kruemelkatze** [comment]
This was changed in today's **v2.0.0** release! Thanks for bringing this up!

**Comment by deadcoder0904** [comment]
Works as expected 💯
