### ISSUE TITLE
Add as a work-space

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#31]
When starting Dashboard, is it possible to have Dashboard add its self as a new workspace ?

**Comment by Kruemelkatze** [comment]
Do you mean a project tile for the Dashboard itself?

**Comment by SheepDomination** [comment]
Yes, although it depends on how it was planned on being added ? When one starts dashboard, a new workspace is created there for separating its self from any current work workspaces.

**Comment by Kruemelkatze** [comment]
I don't quite understand what you mean with adding "the dashboard as a new workspace.

Opening the dashboard simply opens it in a new tab, which is handled like a file. Do you mean that the dashboard should be listed below other workspaces in a multi-workspace environment? Like here indicated in green:
![image](https://user-images.githubusercontent.com/5564731/74547952-36e0ce00-4f4d-11ea-8199-a5bb6968872e.png)

**Comment by SheepDomination** [comment]
It should be listed below another workspaces, but not; within another workspace, rather, completely separate workspace unto its self. 

The current version of dashboard, when it is opened and you click on a tile within dashboard; you are prompt what to do with all the previous opened tabs in the current workspace, whether to save them, close the tab etc.  

By having dashboard open its self as a completely different workspace, it allows the user to switch between workspaces, that being; between dashboard and whatever other workspaces the user has.

**Comment by Kruemelkatze** [comment]
So basically... opening the clicked project in a new window of VSCode?

**Comment by SheepDomination** [comment]
That is where it differs, rather then a new window; if it's possible to take the previous workspace and place it as a temporary tile ?

**Comment by Kruemelkatze** [comment]
I see, it's the behavior we discussed in #28 , right? At least it sounds very similar.

**Comment by SheepDomination** [comment]
It sound familiar but, rather then appending; instead, creating another workspace.  If you can take the current workspace and place it as a tile within dashboard, which means bundling all the current workspace tabs into a tile, then when one opens a tile in workspace they can simply switch between the dashboard workspace, so to speak; and whatever workspace they were working on previously.

**Comment by Kruemelkatze** [comment]
I understand. So you want so save files 1-10 as a tile (they may be placed across multiple folders) and the same for A-Z.

When you have 1-10 open in your VSCode window, clicking on that second project should switch to A-Z and their open tabs.

Is this correct?

**Comment by SheepDomination** [comment]
When you say, save files 1-10; do you mean saving tabs and in this case you just said an arbitrary number of files (tabs) ?

**Comment by SheepDomination** [comment]
How about switching workspace, switching between the current workspace and dashboard ?

**Comment by Kruemelkatze** [comment]
As I'm still unsure what this function should do and - more importantly - the dashboard should and will not provide any extension workspace juggling features/magic, I will invest no more time in this.

If it is such a crucial feature for you, please feel free to fork the project.

**Comment by SheepDomination** [comment]
I hope you can find a solution; I look forward to it.
