### ISSUE TITLE
Space gap between rows 

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#32]
I've managed to get dashboard layout customized almost how I want it, except for this.  I do not know how to remove the huge space ?
![space_gap](https://user-images.githubusercontent.com/6827459/75743889-9b878100-5ce0-11ea-9cdb-f089c7266452.jpg)

**Comment by Kruemelkatze** [comment]
You can remove the big plus by unchecking this box:
![image](https://user-images.githubusercontent.com/5564731/77774374-3dce2680-704b-11ea-9c8e-2855acd682e9.png)

I don't know where the big gap above is coming from... Maybe it has something to do with that icon? You can check that via the ```Open Webview Developer Tools``` command.

**Comment by SheepDomination** [comment]
Toggling off the `+` helped but the space still exists, although smaller; a little more reduction would help.

**Comment by Kruemelkatze** [comment]
> Could you add a option rather then fighting with style sheets to adjust this height ?

Can you check if this isn't resulting from the icon above, using the Webview developer tools? Currently, I have no clue what is causing the space. It looks like you added the icon as a ::before rule to the color and left the project name blank?

The padding between both projects and groups is around ```20-30px```.  For introducing an option for a fixed height, I think I'd need to rewrite a noticeable part of the CSS and code for variable text size.

**Comment by SheepDomination** [comment]
I'm unable to open the visual studio code web view developer tools when dashboard is open.

**Comment by Kruemelkatze** [comment]
Then we are stuck at guessing.

**Comment by SheepDomination** [comment]
Your suggestion was to use Webview Developer tools to check the styles, I'm only saying it isn't possible ?

**Comment by Kruemelkatze** [comment]
Yes, and as you don't provide any information, I can't do anything about that.

**Comment by Kruemelkatze** [comment]
> I know I could use the Webview Developer tools to modify the styles, maybe recent updates has somewhat prevented this ?

I use it all the time for developing the Project Dashboard. So if something broke this option, it has to be on your side.

Anyway, today's **v2.0.0** update reduced the space below projects when the path is disabled. Additionally, there is now a free-form text setting which you can use for custom CSS. The CSS will be injected as a style tag, so if defined correctly, the rules should override the default ones.

Please refrain from opening issues on how to override specific CSS rules in the Dashboard! Get your webview dev tools working again, it helps a great deal with styling. The Dashboards CSS rules can be looked up here: [SASS](https://github.com/Kruemelkatze/vscode-dashboard/blob/master/media/styles.scss), [compiled CSS](https://github.com/Kruemelkatze/vscode-dashboard/blob/master/media/styles.css)

**Comment by SheepDomination** [comment]
When the dashboard is open you can open which webview development tools; that of vscode ?

**Comment by SheepDomination** [comment]
What is the rule for adjusting the spacing between groups in a workspace, I hope there is a rule for the style sheet; that may be the solution. Therefore I can apply it to the Custom CSS.

**Comment by Kruemelkatze** [comment]
You have to find it out yourself using the devtools. I won't help you with any further customizing rules.

Open the dashboard, focus it, and use this command. If the devtools won't open, something in your vscode setup is broken.
![image](https://user-images.githubusercontent.com/5564731/79439236-dca7cc00-7fd4-11ea-8d7b-cd29f6e458a1.png)

**Comment by SheepDomination** [comment]
I got it sorted out; It is the bottom margin which is what adjusts exactly what I want. Except the rule is not being applied in the Custom CSS part of the settings ?
`body .project {margin:0 20px -110px 0;}`

**Comment by Kruemelkatze** [comment]
If I add this exact rule to my settings, it looks like this (notice the overlapping projects):

![image](https://user-images.githubusercontent.com/5564731/79517980-10740780-8050-11ea-8c4f-fbbd3ed77da2.png)

**Comment by SheepDomination** [comment]
That isn't the case on my end, it moves correctly; although when I try to apply it, it doesn't work ?

**Comment by Kruemelkatze** [comment]
Maybe you have a syntax error when you combined that with the "+" group rule. You have to debug this yourself. Check if it is rendered in the <head> of the webview and see if the rules are applied (but overridden, etc.).

**Comment by SheepDomination** [comment]
I've tried both; `body .project data-id="vexdu1fd0hntjyi58urt" {margin 0 20px -110px 0;}` and
`body .project {margin 0 20px -110px 0;}` with either being the only rule; it doesn't work ?

**Comment by Kruemelkatze** [comment]
Thats because your CSS is invalid ;)

**Comment by SheepDomination** [comment]
I've got it exactly how I want it. 

Although now I'm curious to know what issues you were having doing this adjustment, I think you could add this as an option in the settings.

**Comment by Kruemelkatze** [comment]
It's because of a mixture of the tiles not having a fixed height due to the variable font sizing, option for disabling the path and still needing a somewhat fixed height. There are multiple CSS rules for the padding to handle these cases.

Maybe I could rewrite that and make it an option. I just don't see a reason for doing so. Because if the project padding should be an option, why not all the other padding, font sizes, orderings, border color width, etc.?

Also, I dare to say that the default dashboard looks pretty good and satisfies 100% - 1 of the users. If there is a valid request for an interesting and meaningful option that has practical purposes, like smaller tiles to fit more projects, I'll include it. But a differently sized padding? This certainly does not decide between life and death.

**Comment by SheepDomination** [comment]
> Maybe I could rewrite that and make it an option. I just don't see a reason for doing so. Because if the project padding should be an option, why not all the other padding, font sizes, orderings, border color width, etc.?

Can you make a version so I can try this option and see how it works.

**Comment by Kruemelkatze** [comment]
I'll just quote myself:

> I just don't see a reason for doing so.

**Comment by SheepDomination** [comment]
How about adding an option for custom SVG images, rather then hacking into the settings and applying Base64 encoded images ?

Then base on the size of the image padding can be applied around the image or an option for global padding around the image, specifically the base of the image between groups ? The images are stored locally and loaded.

**Comment by Kruemelkatze** [comment]
The problem is that this saving mechanism can not be used for all use cases, namely when syncing the dashboard using VSCode Settings Sync.

I have evaluated 3 types of saving the images:

- Directly in the settings or storage as SVG or base64: Possible and works everywhere, but makes the settings huge, which may result in unforeseen problems with VSCode itself. Usually, these settings aren't bigger than a few kb, so dumping some 100kb+ images in there may lead to problems.
- Saving the images locally, as you suggested: Best solution when the dashboard is only used on one device. It does not work if the dashboard is synced.
- On the web: Would allow accessibility from everywhere and having a low storage footprint, but is blocked by the webview's Content Security Policy.

There is just no option that can be used for all use cases without leading to unforeseen problems. That's the reason why the Dashboard does not support icons, although I originally intended to.

**Comment by SheepDomination** [comment]
> Saving the images locally, as you suggested: Best solution when the dashboard is only used on one device. It does not work if the dashboard is synced.

Is it possible to add this, and with regards to the Content Security Policy; you mean it doesn't allow images to be loaded from an external source as the web ?

**Comment by Kruemelkatze** [comment]
> > Saving the images locally, as you suggested: Best solution when the dashboard is only used on one device. It does not work if the dashboard is synced.
> 
> Is it possible to add this,

This would exclude a large portion of the users from using images, which I want to avoid. So I'm afraid not. I still think putting the images into the name as HTML is the best solution for now. It works for you and does not confuse or hinder other users.

>and with regards to the Content Security Policy; you mean it doesn't allow images to be loaded from an external source as the web ?

Yes, I have to define the folders where content may be loaded from before building the extension. So it cannot be defined by the user.

**Comment by SheepDomination** [comment]
> Yes, I have to define the folders where content may be loaded from before building the extension. So it cannot be defined by the user.

How about an option to load custom external images whereas the folders as you mentioned are defined or not ?

**Comment by Kruemelkatze** [comment]
This should work.

**Comment by SheepDomination** [comment]
How do I get it to work ? :)

**Comment by Kruemelkatze** [comment]
Install the latest version. I activated it globally for now for images only, which should not be a security issue.

**Comment by SheepDomination** [comment]
How do I load an external image, where is the option ?

**Comment by Kruemelkatze** [comment]
We misunderstand each other. I simply added the rule that external images are allowed to be loaded. You still have to add the <img> HTML tag into name or color.

**Comment by SheepDomination** [comment]
Hopefully in a future release a user can have a dialog menu to choose the image whether locally or remote; in the mean time thanks.

**Comment by SheepDomination** [comment]
External images by means of `file://` and `https://` or one or the other.  I'm attempting to load an image externally by means of `https://` I don't see the image, rather the broken image icon ?

**Comment by SheepDomination** [comment]
`<div style='white';height='100px'><p style='font-size:32px;position:relative;bottom:1.8em'>VEX</p><img src='https://www.fortgordon.com/wp-content/uploads/2014/10/Dominos-Logo-2014-300x230.png height=100px width=100px'/></div>"`

Trying to load an image but instead of the image; all I get is, the broken image icon ?

**Comment by Kruemelkatze** [comment]
Because - again - that's just a whole bunch of invalid HTML. What about checking it first, using any HTML validator?
https://www.freeformatter.com/html-validator.html
