### ISSUE TITLE
Resize the project trigger button

### ISSUE THREAD

**Issue by sisoe24** [Kruemelkatze/vscode-dashboard#34]
Is there a way to make the project trigger button smaller (on the Dashboard page)? So they can fit more on the screen

**Comment by Kruemelkatze** [comment]
You mean making the tiles themselves smaller? I'll have a look if I can make a simple setting for this.

**Comment by Kruemelkatze** [comment]
Today's **v2.0.0** release introduces a *Dashboard: Project Tile Width* setting which allows to adjust the tile width in ```px```. By setting it to ```200``` (px) and unchecking *Display Project Path*, you can achieve something like this (note that you need to reopen the Dashboard UI afterwards):


![image](https://user-images.githubusercontent.com/5564731/79043922-9a604280-7c02-11ea-97b1-a99cfb400698.png)

**Comment by SheepDomination** [comment]
This is a nice addition, but; the height between projects groups needs to be addressed with a similar setting.

**Comment by Kruemelkatze** [comment]
> This is a nice addition, but; the height between projects groups needs to be addressed with a similar setting.

Nope. It's fine as it is.

**Comment by SheepDomination** [comment]
Not when there is custom icons.

**Comment by Kruemelkatze** [comment]
> Not when there is custom icons.

You speak it: Custom. C-u-s-t-o-m.
If you insist on fiddling around with your dashboard and potentially breaking the UI, fine; as I mentioned, there is now even a **Custom CSS** setting. But I won't include any overengineered features or settings because you want a special cake. This is getting ridiculous.

**Comment by SheepDomination** [comment]
I don't want a special cake; at all.  If you put into consideration a custom icon, which could have it's own limits then the setting would adjust the height between groups.  
Speaking of the custom settings in the latest version; the custom project name color requires a hex value ?
