### ISSUE TITLE
Deleted groups do not disappear until vscode restart

### ISSUE THREAD

**Issue by FreifeldRoyi** [Kruemelkatze/vscode-dashboard#37]
After the latest update, groups did not disappear after deleting them. I was able to see the actions on the groups even after pressing delete multiple times.
They only disappeared after a restart to the IDE

**Comment by Kruemelkatze** [comment]
Ah, thought this to be fixed with 2.0.1.

Thanks for reporting, will have a look on this!

**Comment by Kruemelkatze** [comment]
This was a bug related to storage consistency (globalState vs settings). I just released v.2.0.2 that fixes it.

Please note: You may lose the latest changes in the dashboard. Sorry for that!
Having two datasources I do not have full control over gives me headaches... :-)
