### ISSUE TITLE
Project Dashboard (Ctrl +F1) Fails

### ISSUE THREAD

**Issue by dfreedman55** [Kruemelkatze/vscode-dashboard#41]
Error message received:
"Running the contributed command: 'dashboard.open' failed.

I uninstalled VS Code completely (including all extensions).
I upgrade Visual Studio Installer
I reinstalled VS Code from scratch.
Upon opening VS Code for the first time I installed the 'python' extension, then 'project dashboard'.
Ctrl + F1 will not open the dashboard.

I've also tried mapping other keyboard shortcuts but the results are the same.

**Comment by Kruemelkatze** [comment]
Thanks for reporting!
Can you please check these two things:
- Can you execute the "Project Dashboard: Edit Projects" command?
- Are your projects stored in the user settings? "So if Dashboard: Store Projects In Settings" is enabled.
    - If so, can you please post (a redacted version if you like) of the ```dashboard.projectData``` entry?

That error usually happens if the JSON data in the settings is corrupt.

Thanks!

**Comment by dfreedman55** [comment]
Command 'Project Dashboard: Edit Projects' resulted in an erorr:
(Cannot read property 'id' of null.)

I've just installed VScode and started playing with it last night, so I have nothing significant in my settings.json file.  With my python/linter installed, I did notice it's been complaining in particular that it expects an array right where null begins (see in bold below).  If I put [ ]'s around the null and then save the file, the linter stops complaining about it.  

{
    "window.zoomLevel": 1,
    **"dashboard.projectData": null,**
    "python.pythonPath": "C:\\Users\\Dan\\AppData\\Local\\Programs\\Python\\Python37\\python.exe",
    "terminal.integrated.automationShell.windows": "",
    "terminal.integrated.automationShell.linux": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.automationShell.osx": "",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "liveshare.connectionMode": "relay",
    "highlightLine.borderStyle": "dashed",
    "highlightLine.borderWidth": "0.5px",
    "highlightLine.borderColor": "white",
    "prettier.tabWidth": 4,
    "lineEndings.color": "",
    "files.associations": {
    
    },
}

When you ask me if my project are stored in user settings, I'll have to admit I don't know.  I don't really have projects vs workspaces vs folders figured out yet.  It's the main reason I'm trying to install your plugin, so I can figure out how best to manage all of the code I have on disk.  I'm open to any recommendations, I'm sure you have some.  :)  Thanks for the quick reply!

**Comment by dfreedman55** [comment]
I just did a bit of reading about Folder, Project, Workspace.  Seems like any file system Folder you open in VScode automatically becomes a Project with a corresponding ".vscode" file populated into the folder you just opened.  Behaviorally, I see that when you open Folder1, it shows up in the Explorer.  When you open Folder2 it shows up in the Explorer and Folder1 disappears.  In other words, you cannot view more than one folder/project (synonymous) at a time in Explorer.  If I create a Workspace, I can add multiple folders to that Workspace (keep them all open in Explorer at the same time).  Workspaces also come with settings which override (are more specific) than global User settings.  I think that pretty much clears it up.  Now the only thing is how to fix the error so I can run Project Dashboard.  :)

**Comment by Kruemelkatze** [comment]
Thanks for the info! I'm sorry you have complications when just starting with VSCode! I have been using VSCode for some years now and never had any real problems. :)

Hmmm. The extension does not care if there is ```null``` or ```[ ]```, but it doesn't like ```[null]```that's why the command fails if the data is set to that value.

Please try following:

1. Enable this user setting. If it is already enabled, disable it and enable it again.
![image](https://user-images.githubusercontent.com/5564731/80633833-b44eb180-8a59-11ea-8851-c7dae7e408d4.png)
2. Directly edit the user settings like you did before and set ```"dashboard.projectData": null```
3. Reopen VSCode

That should basically reset the dashboard data. If that doesn't help, I'll investigate further. :)

**Comment by Kruemelkatze** [comment]
> I just did a bit of reading about Folder, Project, Workspace. Seems like any file system Folder you open in VScode automatically becomes a Project with a corresponding ".vscode" file populated into the folder you just opened. Behaviorally, I see that when you open Folder1, it shows up in the Explorer. When you open Folder2 it shows up in the Explorer and Folder1 disappears. In other words, you cannot view more than one folder/project (synonymous) at a time in Explorer. If I create a Workspace, I can add multiple folders to that Workspace (keep them all open in Explorer at the same time). Workspaces also come with settings which override (are more specific) than global User settings. I think that pretty much clears it up. Now the only thing is how to fix the error so I can run Project Dashboard. :)


Yes, you got that right! :)

**Comment by dfreedman55** [comment]
Cool, that fixed it.  Dashboard: Store Projects in Settings was never enabled for User or Workspace settings.  I enabled them both.  Then changed [null] back to null and reloaded as directed.  Ctrl +F1 brings up Project Dashboard now, no projects, click to add one.

So how does Project Dashboard integrate with or parallel the information about Folders, Projects, Workspaces above?  Thanks for your help!

**Comment by Kruemelkatze** [comment]
> Cool, that fixed it. Dashboard: Store Projects in Settings was never enabled for User or Workspace settings. I enabled them both. Then changed [null] back to null and reloaded as directed. Ctrl +F1 brings up Project Dashboard now, no projects, click to add one.

> So how does Project Dashboard integrate with or parallel the information about Folders, Projects, Workspaces above? Thanks for your help!

Good to hear!
Dashboard uses a custom concept of projects, which may either be files, folders, workspaces or remote projects (opened via the SSH Remote extension). Basically everything that you can open in VSCode.

I'll close this ticket for now, as the original problem is resolved! :)
