### ISSUE TITLE
Is there a way that the Dashboard can open an existing workspace?

### ISSUE THREAD

**Issue by zoredache** [Kruemelkatze/vscode-dashboard#44]
Basically I am wishing there was a 'workspace' project type that just had the path for the workspace configuration file, and then did a `workbench.action.openWorkspaceInNewWindow` or `workbench.action.openWorkspace` for that file.

**Comment by Kruemelkatze** [comment]
Do you mean multi-folder workspaces which are then saved as a ```WorkspaceName.code-workspace``` file?

**Comment by zoredache** [comment]
Yes, by workspace I mean the the stuff that is saved in the `.code-workspace` file.  But that file is more then just a way to just have a project with multiple folders. It can act as a scope for configuration settings.

So lets say I want to have various personal settings for a project, but not modify the `.vscode/settings.json` since that is included in our VCS so everyone has some settings that are identical for everyone.  But everyone doesn't want to be forced to use my theme for a given project, and I want different themes for a couple projects. I apply my theme in the workspace. I also have various other configuration settings to make vscode work my way, but other members of team don't like, so can't be added to the folder settings.

**Comment by Kruemelkatze** [comment]
I understand! I'm using them myself. :-)

I was just asking because the dashboard already includes that option. When adding a project, select the project type **File or Multi-Root Project** and pick the **.code-workspace** file. When you open that project via the dashboard, all workspace settings are applied as usual. I just tested it out by setting the theme in the workspace settings and opening the workspace project. Is this the functionality you are asking for?

I'll probably rename that project type to **Workspace or File Project** makes more sense.

**Comment by zoredache** [comment]
Yes, that does what I want.  Sorry for time wasting.

> I'll probably rename that project type to Workspace or File Project, makes more sense

Renaming it might help.  Or perhaps just adding a note about what the different project do in the in the [configuration section](https://github.com/Kruemelkatze/vscode-dashboard#configuration) of your README.

**Comment by Kruemelkatze** [comment]
> Yes, that does what I want. Sorry for time wasting.

No problem! This was just an indicator that the function is not clear.

> > I'll probably rename that project type to Workspace or File Project, makes more sense
> 
> Renaming it might help. Or perhaps just adding a note about what the different project do in the in the [configuration section](https://github.com/Kruemelkatze/vscode-dashboard#configuration) of your README.

I guess I'll stick with renaming. Hardly anybody reads READMEs anyway. ;)
