### ISSUE TITLE
Ability to add Workspace files

### ISSUE THREAD

**Issue by wapenshaw** [Kruemelkatze/vscode-dashboard#45]
As of now, we only can add folder projects, it would be great if we can open the workspace files that we have saved for a custom workspace instead of just the folder in that workspace.

**Comment by Kruemelkatze** [comment]
Hi!
This was asked just a few days ago: https://github.com/Kruemelkatze/vscode-dashboard/issues/44

You can already add workspaces by selecting **File or Multi-Root Project** in the first selection when adding a project.

As said in #44, I will rename that function so that it is more obvious. :)

**Comment by wapenshaw** [comment]
Heyo! It works! My bad I only checked open issues when searching!

**Comment by Kruemelkatze** [comment]
No problem! :)

I just released v2.2.0 which includes the renamed option and some other changes.
