### ISSUE TITLE
Backup feature: import-export json configuration of all projects

### ISSUE THREAD

**Issue by gabrielspinoza** [Kruemelkatze/vscode-dashboard#52]
It would be great if we could export our projects configuration just in case something crashes.

**Comment by Kruemelkatze** [comment]
Actually, you already can. The command **Project Dashboard: Edit Projects** opens the project data as a JSON file, which you can then just save anywhere. Importing works just the other way around: Copy the backup file's contents and paste it in the file opened by the command.

Is it that what you are looking for? :)

**Comment by gabrielspinoza** [comment]
> Actually, you already can. The command **Project Dashboard: Edit Projects** opens the project data as a JSON file, which you can then just save anywhere. Importing works just the other way around: Copy the backup file's contents and paste it in the file opened by the command.
> 
> Is it that what you are looking for? :)

Yeah that's just what I was looking for, Thanks!

**Comment by Kruemelkatze** [comment]
No problem! Glad that I could be of help.

Just for your information: The file that is opened with this command isn't actually the real data storage, it's just a temp file for editing it. Depending on your settings, the project data is saved either in the vscode storage (globalState) or in your user settings.

**Comment by gabrielspinoza** [comment]
I also noticed that, thanks!
