### ISSUE TITLE
Setting to open project in new window

### ISSUE THREAD

**Issue by jafri** [Kruemelkatze/vscode-dashboard#53]
Can there be a setting to always open projects in new windows (unless project already open in another window or empty workspace)

Currently I have a project open, go to dashboard and click the project. This opens it in the same dashboard, when I actually want to open it as a new window

**Comment by Kruemelkatze** [comment]
You can already open a project in a new window by holding CTRL and clicking or by right click > Open Project in new Window.

I think an additional setting for this would just be an overkill. :-)

**Comment by Kruemelkatze** [comment]
I'll close this issue for now, as this behavior can be achieved by the means described above, and I think an additional setting for this would be just an overkill. :-)
