### ISSUE TITLE
Placing dashboard in another side bar breaks side bar

### ISSUE THREAD

**Issue by GammaGames** [Kruemelkatze/vscode-dashboard#54]
I noticed there was a new dashboard icon, so I moved it into the explorer side bar. This made it so I couldn't open the explorer at all:

![Screen record from 2020-11-23 10 22 03](https://user-images.githubusercontent.com/7832163/99994057-c1c0e580-2d75-11eb-878e-7f7809d25170.gif)

Reinstalling does not fix the issue, vscode remembers the location and puts it back when I reinstall.

Edit: For more info, this feature was added back in May: https://code.visualstudio.com/updates/v1_46#_flexible-layout

**Comment by Kruemelkatze** [comment]
Ah, i see!
Didn't even know that one can put sidebar views into other sidebars. I'll have a look on this right now.

**Comment by Kruemelkatze** [comment]
I just drafted a "fix" for this in version 3.0.1.

**Comment by GammaGames** [comment]
That's fine, I realized as I did it that bad things were probably about to happen. I backed up my config before removing anyway, so in the long run it's just a minor hiccup

**Comment by Kruemelkatze** [comment]
Many thanks for reporting this issue nonetheless! The 2.3.1 update is now live. Please let me know if you encounter any other problems.
