### ISSUE TITLE
use dashboard color for title and/or activity bar

### ISSUE THREAD

**Issue by JohnDoe2991** [Kruemelkatze/vscode-dashboard#55]
First let me tell you that i love your project dashboard. It makes working with multiple projects so much easier!

I usually open multiple instances with different projects and I often get confused which window contains which project. Especially if I don't have all instances in the foreground at the same time.
It would be really helpful to change the title and/or activity bar color according to the project color in the dashboard. That would make distinguishing between the different projects very easy!

**Comment by Kruemelkatze** [comment]
Hi! Thank you for your appreciation! :)

I think what you are looking for is already offered by the [Peacock extension](https://github.com/johnpapa/vscode-peacock). I think it works out of the box in combination with the dashboard. The only thing that's currently not possible is to automatically take the dashboard project's color.

**Comment by JohnDoe2991** [comment]
That's pretty much what is was looking for. I just copy the color codes from the project dashboard to Peacock.
Thank you for the recommendation!
