### ISSUE TITLE
Exactly how can I write the correct CSS script to set for example Custom Project Card Background?

### ISSUE THREAD

**Issue by dotvihar** [Kruemelkatze/vscode-dashboard#57]
Hi,
I try setup Custom Project Card Background with CSS snippet, but it does not work. Can u share with me an exact syntax or an example about it?

**Comment by dotvihar** [comment]
For example how can I set up linear-gradient?

**Comment by Kruemelkatze** [comment]
I think the best way to figure out the rules is to open the webview's developer tools (Command **Developer: Open Webview Developer Tools**) and look at the DOM structure.

For setting the background for all project cards, the CSS could then be like this:
```
body .project {
    background: linear-gradient(45deg, black, orange);
}
```

Targeting a specific project would require specifying the ```data-id``` attribute. You can find that id out via **Project Dashboard: Edit Projects**.
```
.project[data-id="vscodedashboardw263wbutrk1h0f684"] {
    background: red;
}
```

Hope, that helps! :)

**Comment by Kruemelkatze** [comment]
As I didn't hear anything anymore of this, I'm closing this issue. :)
