### ISSUE TITLE
Wrong color

### ISSUE THREAD

**Issue by duongdominhchau** [Kruemelkatze/vscode-dashboard#58]
`Dark Blue` is displayed as a light red color.

![image](https://user-images.githubusercontent.com/56427890/110216120-f1889900-7edf-11eb-9262-41283e8ebd94.png)

**Comment by Kruemelkatze** [comment]
Hey! I guess, you are using a custom theme?
The predefined colors are named after their appearance in the in-built themes. In this case, dark blue is blue in all in-built themes, but is actually the color variable ```--vscode-gitDecoration-conflictingResourceForeground```. So if your theme makes this variable color red, it's also red in the Dashboard.

Naming the color based on their appearance in a custom theme would be quite a hassle. So we have to live with small naming inconsistencies here. :)

**Comment by duongdominhchau** [comment]
Weird, some days ago I installed some color themes but removed them all right after I saw their paleness. My current color theme is **Dark+ (default dark)**. This can be reproduced even when all other extensions are disabled.

I didn't change the color in `settings.json` too
```json
{
  "window.zoomLevel": 1,
  "editor.renderWhitespace": "all",
  "explorer.confirmDelete": false,
  "editor.renderControlCharacters": false,
  "editor.detectIndentation": false,
  "editor.fontWeight": "400",
  "editor.fontFamily": "'Fira Code', 'Source Code Pro', monospace",
  "editor.fontLigatures": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "editor.rulers": [100],
  "todo-tree.tree.showScanModeButton": false,
  "editor.multiCursorModifier": "alt",
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[svelte]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "rust-analyzer.checkOnSave.command": "clippy",
  "rust-analyzer.server.path": "/usr/bin/rust-analyzer",
  "update.showReleaseNotes": false,
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "update.mode": "none",
  "editor.minimap.renderCharacters": false,
  "dashboard.projectData": null
}
```

**Comment by Kruemelkatze** [comment]
Thanks for reporting and having a look! I digged a bit into it and found this:
https://github.com/microsoft/vscode/issues/115801

Apparently they changed this color in the latest update - which i just installed today after testing. ;)

I will replace the Dark Blue entry with the previous value in the next update.
