### ISSUE TITLE
Add multiple projects

### ISSUE THREAD

**Issue by George-Miao** [Kruemelkatze/vscode-dashboard#59]
Hi! I just started using this awesome extension. However, there are tens of projects I want to add to the dashboard. Is it possible for me to add multiple folders into the dashboard at one time? I manually add multiple entries into the config files as a workaround. However, if you can add a command or procedure etc., it would be helpful.

**Comment by Kruemelkatze** [comment]
Hey! Thank you! :)

As you are not the first one to suggest this, I'll add such a feature to the extension. But will most likely offer it only as command (and not in the UI), as it is not something that users do on a regular basis.

I think of such a use case:
1) Execute command *Project Dashboard: Bulk add projects*.
2) File picker opens, allows selecting multiple folders/.vscode-workspace files.
3) After selecting files, you have to select a project group from a dropdown (same as in the *Add Project* command ).
4) All these folders are added with random colors to the selected group.

I'll also think about making a second *Project Dashboard: Bulk add project groups* command to select multiple folders, add them as groups, and their subfolders as projects.

**Comment by George-Miao** [comment]
That sounds great to me! Looking forward for updates <3
