### ISSUE TITLE
Feature Request--Add current project to dashboard

### ISSUE THREAD

**Issue by Victarry** [Kruemelkatze/vscode-dashboard#64]
I think it will be very convenient if I can directly add current project to project dashboard instead of manually adding it through the full path.

**Comment by Kruemelkatze** [comment]
All the data of the current workspace should be pre-filled when adding a new project. So adding your current workspace should only be confirm > confirm > confirm. Adding an extra option would only omit name and path, so I don't think that's worth it, :)
