### ISSUE TITLE
Update package.json to ensure extension can run in different extension host setups

### ISSUE THREAD

**Issue by bamurtaugh** [Kruemelkatze/vscode-dashboard#65]
Hi! I'm from the VS Code team, and we'd like to ensure VSCode Project Dashboard can run in the different extension host setups VS Code currently supports. I've found that the current definition of `extensionKind` for your extension is too restrictive.

The extension has the `extensionKind` set to `["ui"]`: https://github.com/Kruemelkatze/vscode-dashboard/blob/master/package.json#L11. This defines that the extension can only run in the VS Code desktop extension host. 

However, this extension can also run on the workspace extension host (which is used for remote scenarios) since it doesn't have any dependencies on the desktop extension host. It'd also be great to enable it for Codespaces web.

Thus, to ensure your extension can run properly across setups, we'd recommend to change the extensionKind to `"extensionKind": ["ui", "workspace"]`. More information about `extensionKind` can be found [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location).

Please let me know if you have questions - I'm happy to help clarify anything. Thank you!

**Comment by Kruemelkatze** [comment]
I changed this and just released version 2.3.2 (already live on the Marketplace).

**Comment by bamurtaugh** [comment]
Thanks so much for the quick action and response! 🚀
