### ISSUE TITLE
Open Project in new window by wheel-click

### ISSUE THREAD

**Issue by creage** [Kruemelkatze/vscode-dashboard#67]
Same as links open in modern browsers.

**Comment by Kruemelkatze** [comment]
That's actually a good idea. Honestly, I don't know why I havent thought of this. I just published a new release that should be live soon.

Thanks for suggesting!

**Comment by creage** [comment]
@Kruemelkatze this feature stopped to work after some of the latest releases :(

**Comment by Kruemelkatze** [comment]
> @Kruemelkatze this feature stopped to work after some of the latest releases :(

Thanks for reporting! I just released a new version that fixes this!
