### ISSUE TITLE
Feature request: open dashboard on VSCode startup

### ISSUE THREAD

**Issue by bimbo1989** [Kruemelkatze/vscode-dashboard#7]
I don't know if VSCode allows the override of the startup screen, but it would be nice to have the dashboard opening instead of the last project used (of course with a setting so the user can decide whether to have this feature enabled or not).

**Comment by GammaGames** [comment]
Mine automatically opens the dashboard if there's no active project, you can force it to be an empty project with the following settings:
```
"workbench.startupEditor": "none",
"window.restoreWindows": "none"
```

**Comment by bimbo1989** [comment]
Uh, it works!
No need for the feature then, I'm closing the issue 😄

**Comment by GammaGames** [comment]
@alexweininger Since you thumbed this issue, I'm tagging you so you can see how it was solved.

**Comment by Kruemelkatze** [comment]
I didn't even see this issue, thanks for resolving it by yourself. :)
As @GammaGames mentioned, the dashboard shows when a new VSCode window without workspace or file is opened.
