### ISSUE TITLE
its possible connect to remote folder using sftp for example?

### ISSUE THREAD

**Issue by ivan-vilches** [Kruemelkatze/vscode-dashboard#70]
its possible connect to remote folder using sftp for example?

**Comment by Kruemelkatze** [comment]
Vscode dashboard does not provide any features for remote connections itself and just used the API provided by vscode. The SSH connection you can select when creating projects just calls the SSH Remote extension. So no, this is not possible.

If you need this feature, I'd suggest looking for an (s)ftp extension ([the vscode-sftp](https://marketplace.visualstudio.com/items?itemName=liximomo.sftp) seems to be build around syncing?) and see for yourself how the dashboard could integrate with it (usually by commands). I'll then gladly accept a PR for this. :)
