### ISSUE TITLE
How to add a target folder to ssh remote?

### ISSUE THREAD

**Issue by TarunGunampalli** [Kruemelkatze/vscode-dashboard#71]
I'm trying to set up a project on a remote ssh and I'm wondering how to add a target folder when I input the route.

Update: I got it, but how can I use the ~ to go directly into my home directory? It seems like I have to start the path with the / at the root, but can I start in ~?

**Comment by Kruemelkatze** [comment]
Did you figure it out? The dashboard is just using the ssh-remote extension's API, so you have to look there I guess. :)

**Comment by srosenzweig09** [comment]
Please share how you got it. I am having this issue now and would appreciate some help! Thanks!

**Comment by TarunGunampalli** [comment]
I was never able to start the path from something other than the root. You just have to specify the full root path.

**Comment by Kruemelkatze** [comment]
> I was never able to start the path from something other than the root. You just have to specify the full root path.

I also think so. At least I couldn't find any information on that in the ssh-remote extension's docs. I just want to clarify again that the dashboard does not open any kind of project itself, it just uses vscode's or in this case the ssh-remote extensions API. So it seems like this is a limitation of the ssh extension.

**Comment by SheepDomination** [comment]
When adding an SSH folder, one is getting asked for the password for the remote folder to connect too but nothing connects instead a failure ?

When restarting VSCode, and starting dashboard I have for testing one SSH remote tile at the top of the VSCode Window, it lists the remote host to connect too which is correct, then askes for a password; when I enter in the password it fails to connect to the remote SSH host for the tile ?
