### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError

### ISSUE THREAD

**Issue by davidmwhynot** [Kruemelkatze/vscode-dashboard#77]
Issue Type: <b>Bug</b>

1. Upgrade to latest version of VSCode.
2. Open Project Dashboard

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

Extension version: 2.5.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 3181)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.83GB (26.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 190eddc9-e202-47b2-ac70-35e7f80a2140|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Kruemelkatze** [comment]
Sorry, missed this issue somehow!
Is this still happening for you? I'm using VSCode + Dashboard daily but it never happened to me.
