### ISSUE TITLE
Please add "description" line

### ISSUE THREAD

**Issue by yalondpsi** [Kruemelkatze/vscode-dashboard#78]
Hi @Kruemelkatze ,
I find this extention very usefull.
What is missing is one more line in a project's card : description.
It will be great if a user can add his own description for a project.

Thank you
Yalon

**Comment by Kruemelkatze** [comment]
Sorry for the late answer. I think this would bloat the dashboard, as the UI as of now is already quite space-consuming. But if you find a nice way of integrating it, I'll gladly have a look at it!
