### ISSUE TITLE
RFE:  Color open VS Code Menu bar with selected dashboard color

### ISSUE THREAD

**Issue by wtflanders** [Kruemelkatze/vscode-dashboard#80]
Hi - love the plugin.  Is it possible to color the VS Code Menu header bar with the selected dashboard color?
i.e. something like this - when you hover the mouse over the vs code task bar icon/button on the bottom of the desktop:
![image](https://user-images.githubusercontent.com/43656560/154520054-757ba651-63a0-4f8c-9207-2ed2fbaae2aa.png)

It would make it much easier to navigate between VS Code instances when you are working on multiple projects simultaneously.
Thanks!
Bill

**Comment by Kruemelkatze** [comment]
Hi! This has been discussed once: [https://github.com/Kruemelkatze/vscode-dashboard/issues/55](https://github.com/Kruemelkatze/vscode-dashboard/issues/55).

You can use the [vscode-peacock extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) for that. I didn't find a robust solution for syncing the colors between those two extensions back then, so you have to manually set them.

But apart from that, I think that's exactly what you want. :)

**Comment by wtflanders** [comment]
Thank you, I will check it out!

________________________________
