### ISSUE TITLE
Question concerning syncing

### ISSUE THREAD

**Issue by thistlillo** [Kruemelkatze/vscode-dashboard#81]
[Here ](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard) I read:
```
Projects are stored in the globalState by default (saved on the machine) but can be set to be saved in the settings (to be synced via [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)) instead. Note that by doing so, you remove the possibility of having different dashboards on your synced devices.
```

My question is: what am I supposed to do in order to sync the settings syncing via the "Settyngs sync" (that I have already installed)? I tried to search for "dashboard" in my preferences.json, but could find only: `"dashboard.projectData": null`. In the preferences of "Settyings sync"  I did not find any references.

**Comment by Kruemelkatze** [comment]
You can enable storing the dashboard data in Settings > Extensions > Project Dashboard. The dashboard data will then be migrated. I would suggest backing up the data by saving the file display by the command "Project Dashboard: Edit Projects". Just to be save. :)

![image](https://user-images.githubusercontent.com/5564731/155702811-41602002-6fa1-49d7-97f8-01fc65e6c6c0.png)

However, I noticed that my setup of Settings Sync now also syncs the dashboard data when it is in the default global storage. So maybe you can enable that in Settings Sync.

**Comment by thistlillo** [comment]
Is there any way to export the settings without relying on the Settings Sync (asking because I do not use that extension)?

**Comment by Kruemelkatze** [comment]
Yes, you can access the Dashboard data by the command ```Project Dashboard: Edit Projects```
Then save the file somewhere else or copy it's content. You can then paste the content when editing the projects on another computer.

**Comment by Kruemelkatze** [comment]
As mentioned in the other issue:

>  The latest version 2.6.0 includes a fallback for the rare case of missing dashboard data after syncing. As I haven't have any new information, I'll close this for now.
