### ISSUE TITLE
Feature request: Color from the git repository

### ISSUE THREAD

**Issue by GoudronViande24** [Kruemelkatze/vscode-dashboard#82]
I would love if the plugin allows to automatically get the color based on the GitHub repository of the project. 

Example: add a project in the dashboard, then if the project is detected to be a github repo, ask if the color should be the repo's color (yellow for js, orange for html, etc.)

If possible, it could be cool if the colored bar is the same as the one from the github repo. Examples:
![image](https://user-images.githubusercontent.com/42936037/157350236-5551fb65-2d4f-49c0-8c9b-eb06fedba2ee.png)
![image](https://user-images.githubusercontent.com/42936037/157350402-aa68b3b2-119f-4aa5-bbd9-2f8066da15c3.png)

This extension is very great, thank you for making it !

**Comment by Kruemelkatze** [comment]
Hi! 

While interesting, this seems quite a change for a small UI feature. At the moment, the dashboard has no dependencies to GitHub whatsoever, I only check if the folder is a Git repository. So I'm afraid I won't implement this anytime soon.

But you can set a projects color manually by providing a CSS gradient. While this will not be a live view of the GitHub repo's colors, you can at least achieve a similar effect with just a little bit of setup.

**Comment by GoudronViande24** [comment]
Yeah that's what I do actually. Thanks you.
