### ISSUE TITLE
Relative path support

### ISSUE THREAD

**Issue by acid-srvnn** [Kruemelkatze/vscode-dashboard#85]
Hi. Thanks for the extension.

Would it be possible to give relative path support ? 
like "path" : "../project2"

I am planning to save dashboard.projectData in my workspace file and it will be linked to other projects relatively.

**Comment by Kruemelkatze** [comment]
This has been included in the latest version 2.6.0. Please note that relative paths only work when a workspace is already open. Hope that fits your use case.
