### ISSUE TITLE
Issues with syncing

### ISSUE THREAD

**Issue by thistlillo** [Kruemelkatze/vscode-dashboard#89]
I have problems in syncing projects between (at least) two VSC installation.

The first one (the source), with configured projects, is a linux installation running VSC 1.72.1, Project Dashboard  v2.5.2 and Settings Sync v3.4.3.
The second one (the target) is a windows 10 installation running VSC 1.73.0, Project Dashboard v. 2.5.2 and Settings Sync v3.4.3.

I was able to keep the machines synchronized in the past, but now the target Project Dashbord remains empty. I look also at https://github.com/Kruemelkatze/vscode-dashboard/issues/81, but could not find a solution.

Is there anyone who can suggest what to check?

**Comment by Kruemelkatze** [comment]
That's interesting. I just made a clean installation on my two workstations (both Win11) and both synced without any issues.

Would you mind backing up your Project Dashboard data (Edit Projects Command and then Save As somewhere), then enabling this setting on the source:

![image](https://user-images.githubusercontent.com/5564731/200688445-e95a5fb3-b462-4e39-9996-44f2f15e6266.png)

Then uploading your settings and downloading them again on the target.

**Comment by Kruemelkatze** [comment]
The latest version 2.6.0 includes a fallback for the rare case of missing dashboard data after syncing. As I haven't have any new information, I'll close this for now.
