### ISSUE TITLE
CustomCSS is not working

### ISSUE THREAD

**Issue by BergkampHUN** [Kruemelkatze/vscode-dashboard#91]
The customCSS field is not working properly.

It's only working if you write the customCss like this: customCss = '</style><style>body {...}'

**Comment by BergkampHUN** [comment]
Created a pull request with the fix: https://github.com/Kruemelkatze/vscode-dashboard/pull/90

**Comment by Kruemelkatze** [comment]
Ah, I see, thanks for the PR! 
Totally missed it as (almost) no one uses this option. :)

**Comment by BergkampHUN** [comment]
It was needed for me to have a nice custom background gradient for the body tag.
I've just found you awesome extension, and I've just started to play with it and customize everything.
Thank you for this extension!

**Comment by Kruemelkatze** [comment]
This has been shipped with the latest version v.2.6.0. Thanks for fixing!
